name = "tinyblog"
license = "MIT"
licenselink = "https://marcusb.org/hacks/MIT-LICENSE.txt"
description = "Hyper minimal blog theme for Hugo"
homepage = "https://marcusb.org/hacks/tinyblog.html"
demosite = "https://marcusb.org/"
tags = ["blog", "minimal"]
features = ["responsive"]
min_version = "0.134.0" # .Summary | plainify lossage

[author]
  name = "Marcus Butler"
  homepage = "https://marcusb.org"
