baseURL = 'https://tinyblogexample.marcusb.org/'
languageCode = 'en-us'
title = 'Tinyblog Demonstration Site'
markup.highlight.noClasses=false

[module]
[[module.imports]]
        path = 'github.com/marcus0x62/tinyblog'
[[module.imports]]
        path = 'github.com/marcus0x62/tinycomments'
[[module.imports]]
        path = 'github.com/marcus0x62/tinyimages'

[params]
    author = "Marcus Butler"
    licenseText = "Tinyblog is licensed under the MIT License"
    licenseLink = "https://marcusb.org/hacks/MIT-LICENSE.txt"
    #accentColor = "grey"
    #textColor = "black"
    #backgroundColor = "#fefbea"
    #navbarBackgroundColor = "#ffffea"
    #navbarBorderTop = "2px"
    #navbarBorderBottom = "1px"
    #navbarIconSize = "16px"
    #itemsPerPage = "5"

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/tinyblog.html"
    name = "Tinyblog"
    weight = 2

[[menu.main]]
    url = "/tinycomments.html"
    name = "Tiny Comments"
    weight = 3

[[menu.main]]
    url = "/tinyimages.html"
    name = "Tinyimages"
    weight = 4

[[menu.icon]]
    url = "/contact.html"
    name = "contact"
    [menu.icon.params]
        icon = "/images/envelope.svg"
    weight = 1
